

# XP/Levels system
xp:
  per_message: 10        # XP awarded per message
  cooldown_seconds: 60   # User can only gain XP once per minute
  max_xp_per_day: 500    # Optional daily cap per user

levels:
  level_roles:           
    5: "Bronze"
    10: "Silver"
    20: "Gold"
    50: "Diamond"
  badges:                
    5: "Beginner"
    15: "Active"
    30: "Veteran"

# Spam prevention
spam:
  max_messages: 5        # Max messages in time window before warning
  per_seconds: 10        # Time window in seconds
  mute_duration: 300     # Seconds to mute user (if supported)

# Auto-role on join
auto_role:
  enabled: true
  role: "Member"         # Default role assigned to all new users

# Moderation settings
moderation:
  warn_threshold: 3      # Number of warnings before mute/kick
  mute_duration: 600     # Mute length (seconds)
  kick_threshold: 5      # Number of warnings before kick
